### ISSUE TITLE
No label on Leaflet non-point layers

### ISSUE THREAD

**Issue by MickaelH974** [tomchadwin/qgis2web#127]
Hi,

First very good job for this plugin. 

I think i will try to create a MaterialDesign template for html export.

So my problem is that i can't see label on leaflet option but without error message. Can you help me?

![qgis2web](https://cloud.githubusercontent.com/assets/14918925/10213059/362b8394-6819-11e5-8dad-b9c27276a372.PNG)

Thanks.

**Comment by tomchadwin** [comment]
See #24. I'll have another look at Leaflet labels for non-point layers. I can't remember what the problem was.

**Comment by tomchadwin** [comment]
If there's a still a roadblock to this request, I'll see if I can remove the Label checkbox from non-point layers (when Leaflet is selected as the output map format). That should give users more realistic expectations.

**Comment by MickaelH974** [comment]
Ok,
Effectively it work with point-layer, i think i will try to do with it.
Thank a lot.

**Comment by dpsspatial** [comment]
I'm not able to get the labels to display on point layers at all...

**Comment by tomchadwin** [comment]
@dpsspatial Can you follow the debugging instructions on the Help tab of the plugin (or the homepage of the plugin here on Github) to try to help narrow down where the problem might be?

**Comment by dpsspatial** [comment]
@tomchadwin turns out it wasn't labeling INT fields, only Character... so I have a workaround for now, but is this expected?

**Comment by tomchadwin** [comment]
Ah, OK. Let me look at that. In the meantime, create a new text field with the numeric values in it as a string.

**Comment by tomchadwin** [comment]
I've commited a fix for OL3 maps - can you test? Leaflet to follow.

**Comment by dpsspatial** [comment]
Upgraded to version 1.3.2:

The INT labels show undefined and the symbols don't take:

![ol3_undefined](https://cloud.githubusercontent.com/assets/12851723/13883497/555eef48-ecef-11e5-9048-551282e17d26.PNG)

Additionally, the OL3 version seems to pick up the data twice in the map, so when you preview the project, you see nothing in the preview map until you zoom out, where I see two versions of the same dataset:

![ol3_double](https://cloud.githubusercontent.com/assets/12851723/13883526/712d6a4c-ecef-11e5-94fd-7bbf1dd40c57.PNG)

Zooming in to either of the 'undefined' shows the same as the image above...

Thanks for your help/work, Tom!!!

**Comment by tomchadwin** [comment]
Confirmed - apologies. Broken as part of fixing the 2.5d renderer bug. Looking into it now.

**Comment by tomchadwin** [comment]
I've committed a possible fix to master - can you test?

**Comment by dpsspatial** [comment]
I hope I've upgraded the plugin correctly (re-install as no update was showing, but still using v. 1.3.2)

- in OL3, not seeing the duplicate dataset in map preview
- OL3 still showing 'undefined' w/ no symbols on INT type fields
- Leaflet not showing INT labels...

**Comment by tomchadwin** [comment]
No, you need to overwrite manually from Github master branch - see the help tab or README.

**Comment by dpsspatial** [comment]
Got it - 

- OL3 showing INT labels!

Thanks, Tom!

**Comment by tomchadwin** [comment]
Great. Still not managed to fix the issue in Leaflet exports yet.

**Comment by dpsspatial** [comment]
Appreciate your help - let me know if I can test anything else...!!!

**Comment by tomchadwin** [comment]
Hopefully this can now be fixed, since Leaflet1 has native `L.Tooltip`, and I guess it works for non-point geometries.

**Comment by Sandro88033** [comment]
Hi Tom, I have something similar, I tried to find out the problem, I import my data from CSV file to QGIs then convert to shapefile, when I use QGIS2WEB, the data shows as "undefined", could you help me with this please.

![image](https://user-images.githubusercontent.com/29586309/27363273-93c987e0-5687-11e7-8917-bbcb511d2c8a.png)

**Comment by tomchadwin** [comment]
@Sandro88033 Can you upload the Shapefile, and also export and upload the layer's style as a .qml?

**Comment by Sandro88033** [comment]
[Reactive.zip](https://github.com/tomchadwin/qgis2web/files/1120712/Reactive.zip)  

I dont know whether is the correct info.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by tomchadwin** [comment]
@Sandro88033 I don't think that's anything to do with this issue, which relates to labels, not popups. However, can you try giving your columns names with no special characters in them? Specificaly, rename "JOB#" to "JOB". Let us know if that works. If not, try removing the spaces in the other column names. You can always give each column an alias with the spaces back in to make the webmap more readable.

Let us know if you get it working.
