### ISSUE TITLE
Failed to show wms layer images in leaflet webmap

### ISSUE THREAD

**Issue by jie4922** [tomchadwin/qgis2web#396]
HI!

I've noticed wms layer images can't be shown in qgis2web preview window or after being exported might be due to  leaflet version was upgraded to 1.0.0. Because wms layer is only worked with qgis2web V1.18 (or earlier version ) and no matter using qgis2.14 or 2.18.
Now I can only use the old version qgis2web to produce my map.
That wms server is public and url :  http://wms.nlsc.gov.tw/wms
Thanks for check this situation.
Your qgis2web is a very useful work. Thank you for developing that so hard!

**Comment by tomchadwin** [comment]
Is it not working in both OpenLayers 3 and Leaflet exports?

**Comment by jie4922** [comment]
Both not working now and always not working in OL3 since I started to use qgis2web about 1 year ago.

**Comment by tomchadwin** [comment]
OK, I've confirmed that a different WMS does work in both OL3 and Leaflet, but I've confirmed that your WMS does not work. I don't understand why.

Can anyone else help?

**Comment by tomchadwin** [comment]
I've asked for help here:

http://gis.stackexchange.com/questions/226216/cannot-get-specific-wms-to-display-in-leaflet-or-openlayers-3

**Comment by jie4922** [comment]
Thanks a lot! 
Press F12 in preview window can see the message ：
"Resource interpreted as Image but transferred with MIME type text/xml."
Attach the preview window console snapshot for reference~
![logmessage](https://cloud.githubusercontent.com/assets/25398198/22396666/11cca712-e59a-11e6-8fbc-149ef6ffe4cd.jpg)

**Comment by tomchadwin** [comment]
Yes, I've seen that, but it doesn't appear when you export to Chrome, I think, so I'm not so worried about it.

**Comment by tomchadwin** [comment]
Fixed in OL3 export. Leaflet problem persists.

**Comment by tomchadwin** [comment]
Fixed by @jgrocha. Thanks!

**Comment by jie4922** [comment]
Thank you guys! Expect the revised version~
By the way, will WMTS be supported by qgis2web in the future?
Anyway thanks again!

**Comment by tomchadwin** [comment]
I'll try to release v2.3.1 with these fixes as soon as I can. Please let us know if it solves the problem for you. 

It looks as though WMTS could certainly be supported in OpenLayers 3. Leaflet might be more problematic. The WMTS plugin had not been updated for Leaflet vs. However, there's a pull request for it, so it might work.

**Comment by jie4922** [comment]
Sure thing! Will feedback to you right after v2.3.1 being released. Glad to see qgis2web more sophisticated and powerful.

**Comment by tomchadwin** [comment]
Released as 2.3.1 and pushed to QGIS plugins repo.

**Comment by jie4922** [comment]
Hi Tom
Here are several 2.3.1 test results：
1. WMS：
    (1)OL3 still malfunction.
    (2)Leaflet seems work well.
2. "Restrict to extent" (Due to the result 1, I just test in Leaflet)
    (1)Maybe get error message at first, but not always error. Sometimes works by check or un-check 
        visible layers in "Layers and Groups" area.
    (2)Even get the error message, I can un-check the "Restrict to extent" to make preview work, then  
        check this function again and export directly. Seems still work in exported leaflet webmap.
    (3)Error message attached as below：
![default](https://cloud.githubusercontent.com/assets/25398198/22447134/98685c38-e78b-11e6-8c3f-ba0901ed3f17.jpg)

3. Categorization works.
4. Layer order：
   I found that layer order in all panels are just the same as in QGIS, but WMS layer order are reversed in 
   map as below：
![2](https://cloud.githubusercontent.com/assets/25398198/22447320/cf99d5aa-e78c-11e6-91fb-a8d758536815.jpg)

PS: All results were tested by the same layer combination as above.

**Comment by tomchadwin** [comment]
OK, let's try to deal with these one at a time.

> 1. WMS：
> (1)OL3 still malfunction.

I tested with your layer EMAP8, and it works. Can you tell me which layer to test? And can you tell me how it malfunctions? What happens?

> 2. "Restrict to extent" (Due to the result 1, I just test in Leaflet)
> (3)Error message attached as below

Before starting the plugin, can you open the QGIS Python console, and then see what happens? You should get a more useful error reported in that console.

> 4. Layer search (also just test leaflet)

Yes, I want to try to fix that, but I'm not sure how easy it will be, as it uses someone else's Leaflet plugin.

> 5. Layer order

OK, perhaps WMSes don't respect layer order - I'll look into it.

**Comment by jie4922** [comment]
1. WMS OL3：
My layer is "PHOTO2". But I get the same result by trying "EMAP8" layer. The result is just an empty map without error message. See the snapshot：
![default](https://cloud.githubusercontent.com/assets/25398198/22461144/0acd8c9c-e7e3-11e6-8c21-6caf44e3b955.jpg)

2."Restrict to extent"：
It's weird that I start a brand new project importing all layers I need and then error message gone. Follow you suggestion to open python console before executing qgis2web, I get the snapshot for your reference：
![default](https://cloud.githubusercontent.com/assets/25398198/22462397/1681d7b4-e7e8-11e6-8bfc-7073156ba572.jpg)

And the exported map works just as expected.

**Comment by tomchadwin** [comment]
> 1. WMS OL3

Works for me with PHOTO2:

![2017-01-31 11_14_42-export to web map](https://cloud.githubusercontent.com/assets/7840213/22462784/a4a8b504-e7a6-11e6-89f7-8d0c37123de7.png)

**Comment by jie4922** [comment]
I've just reinstall qgis2web and get the same empty OL3 map.
Maybe there is local problem existed in my PC? 
I can try my office PC when back to company.

**Comment by tomchadwin** [comment]
Can you export the map, and, again, look at the browser console (by hitting F12)?

**Comment by jie4922** [comment]
OK, I export and get the browser console snapshot :

![image](https://cloud.githubusercontent.com/assets/25398198/22464127/439093d2-e7f0-11e6-9afb-403ee864d8a9.png)
The exported file (index.html seems not correct? even can't see the wms url)：
https://drive.google.com/file/d/0B01wuahjDBFGVmkzY2NEcWNoN00/view?usp=sharing

**Comment by tomchadwin** [comment]
Is your screenshot the `Console` tab? Looks like it might be the `Sources` tab.

**Comment by jie4922** [comment]
It's console tab, what you see is just due to the mouse cursor stop on the Sources tab when I shot. :)
![image](https://cloud.githubusercontent.com/assets/25398198/22464703/28ed7c2c-e7f3-11e6-9741-fba29c1fa5e9.png)

**Comment by tomchadwin** [comment]
Yes, apologies. I'm now looking at the copy of the output you uploaded. I see what you see. I don't yet understand what the problem is.

**Comment by jie4922** [comment]
Yes, so weird. I've never seen my wms layer ever work in OL3 since start to use qgis2web. 
So I've already ignored OL3 for very long time, thought everybody can't work with OL3.
Just realize my situation is an odd case today. @@
But hope not bother you with my odd issue too much.
Already help me huge a lot~ 
Qgis2web will be core element in my platform building work. Thank you so much!

**Comment by tomchadwin** [comment]
But we can solve this - because I have your copy which is not working, so hopefully we can figure out why. It's an interesting one...

**Comment by tomchadwin** [comment]
OK, the code I just added to make sure we set the WMS version is not working. Let me find out why.

**Comment by tomchadwin** [comment]
Ah, and it's also failing because the layer name has not handled the non-ASCII characters. Things to work on.

**Comment by jie4922** [comment]
OH! But the layer name is english, also have the char problem?

**Comment by tomchadwin** [comment]
I wonder if it is using the layer's `Name`, not its `Title` (look at the `Add WMS` dialog box after you have connected to your server).

**Comment by jie4922** [comment]
Understand what you mentioned. 
In qgis layer panel and qgis2web layer panel both use the "Title" to be layer name instead of the wms list's "name".
But the "EMAP8"'s Title is "taiwane-map(en)", also belongs to different char system?

**Comment by tomchadwin** [comment]
If you double-click your layer in the layers list in QGIS, and click the General tab, you'll see the layer name in your native glyphs. Please don't change that (well, you can to work around the problem for the moment), as I need to get it to work as it is.

**Comment by tomchadwin** [comment]
Could it possibly be that the WMS server has international/localized capabilities, so when I connect to it with an English client, I get English strings, and it works, but when you connect, you get non-Englosh, and it fails. I'm only guessing.

**Comment by jie4922** [comment]
God, I think you are so right! Just after I change the QGIS language setting from Tradtional-Chinese to US english, OL work!
![image](https://cloud.githubusercontent.com/assets/25398198/22466705/752bcb44-e7fc-11e6-9016-cf13ada5e6c3.png)

**Comment by tomchadwin** [comment]
OK, great. So you can get a map working, but can't yet get Traditional-Chinese to work. How do the layers list, popups, and labels work? Do they display the script OK?

**Comment by jie4922** [comment]
All test under English setting and use EMAP8 as basemap.
1.Once import layer which was created under Traditional-Chinese setting will result in the empty OL3.
2.Create new polygon layer under English setting will work. 
3.You mean list , popup and labels of vector layer in OL3 MAP? See screenshot:
![image](https://cloud.githubusercontent.com/assets/25398198/22470191/6f29dbe8-e809-11e6-9ac6-cfcaf1a75aa6.png)
![image](https://cloud.githubusercontent.com/assets/25398198/22470223/8c44a334-e809-11e6-9257-091d634d69fd.png)

PS:I create two features in this new polygon layer, feature#2 contain Tradtional-Chinese attribute value as screenshot#2.

**Comment by tomchadwin** [comment]
If you are happy to copy down master branch from Github, I've just committed some bugfixes which might allow you to use non-ASCII. Could you test it? I don't want to do a release with the changes until they've been tested.

**Comment by jie4922** [comment]
Just try the master branch. 
But even under English the OL3 can't work now. I've try to rename the wms layer's name to english also get empty OL3.

**Comment by tomchadwin** [comment]
OK, can you check the browser console again?

**Comment by jie4922** [comment]
Oops, I find that files are failed to produce. No index.html for browser to open.
![image](https://cloud.githubusercontent.com/assets/25398198/22472970/3119b68a-e812-11e6-91c4-0e6a9b13d154.png)

**Comment by tomchadwin** [comment]
Oh. In that case, I think I need you to check the Python console in QGIS when you run the plugin.

**Comment by jie4922** [comment]
Here!
![image](https://cloud.githubusercontent.com/assets/25398198/22473145/cada74b2-e812-11e6-9e31-50c25a905739.png)

**Comment by tomchadwin** [comment]
I made a couple of mistakes. Trying to find and fix them now.

**Comment by tomchadwin** [comment]
OK, can you try again now?

**Comment by jie4922** [comment]
1.Can't work under Traditional-chinese setting.
![image](https://cloud.githubusercontent.com/assets/25398198/22475326/8f780676-e819-11e6-872a-101203c0c19d.png)
![image](https://cloud.githubusercontent.com/assets/25398198/22475423/e1944866-e819-11e6-8c60-ea50b8ed4880.png)
![image](https://cloud.githubusercontent.com/assets/25398198/22475791/113b1102-e81b-11e6-9cc1-d5be2cf976c2.png)


2.Under English setting, the Traditional-Chinese layer work!
![image](https://cloud.githubusercontent.com/assets/25398198/22475652/99f5e6a8-e81a-11e6-94e4-65f03eed55b8.png)

Seems the same under Traditional-Chinese but work under English environment!

**Comment by tomchadwin** [comment]
OK, great. I think the remaining issue might be because I am trying to detect the WMS by searching for the string "VERSION" in the `getCapabilities()` call. Perhaps your WMS responds in Trad. Chinese, so "VERSION" is not found.

**Comment by tomchadwin** [comment]
No, according to @itjturton on Twitter, that's not the explanation. I'll keep investigating.

**Comment by tomchadwin** [comment]
With your client set to Trad. Chinese, select your WMS in the QGIS layers list, open the Python console, and type the following:

```python
print iface.activeLayer().metadata()
```

Can you paste the output here?

**Comment by jie4922** [comment]
Python主控台
使用iface存取QGIS的API介面或鍵入help(iface) 獲取更多訊息
print iface.activeLayer().metadata()
<p class="glossy">驅動程式</p>
<p>OGC Web Map Service version 1.3 data provider</p>
<tr><td>&nbsp;<a href="#selectedlayers">已選擇圖層</a>&nbsp;<a href="#otherlayers">其它圖層</a></td></tr><tr><th class="glossy"><a name="serverproperties"></a>服務器屬性</th></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>WMS版本</td><td>1.1.1</td></tr><tr><td>標題</td><td>maps.nlsc.gov.tw web map service</td></tr><tr><td>摘要</td><td>Can also generate PNG,JPG</td></tr><tr><td>關鍵字</td><td>WMS<br />maps.nlsc.gov.tw</td></tr><tr><td>線上資源</td><td>-</td></tr><tr><td>聯絡人</td><td>NLSC<br />PG<br />maps.nlsc.gov.tw</td></tr><tr><td>費用</td><td>NONE</td></tr><tr><td>訪問限制</td><td>NONE</td></tr><tr><td>獲取性能地址</td><td>http://wms.nlsc.gov.tw/wms?</td></tr><tr><td>GetMap地址</td><td>http://wmts.nlsc.gov.tw/wms?VERSION=1.1.1&</td></tr><tr><td>獲取圖徵訊息地址</td><td>http://wms.nlsc.gov.tw/wms?</td></tr><tr><td>GetLegendGraphic</td><td></td></tr><tr><td>影像格式</td><td>image/png<br />image/jpeg</td></tr><tr><td>識別格式</td><td></td></tr><tr><td>圖層數量</td><td>19</td></tr></table></td></tr><tr><th class="glossy"><a name="selectedlayers"></a>已選擇圖層</th></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>PHOTO2</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>正射影像圖(通用)</td></tr><tr><td>摘要</td><td>正射影像圖(通用)</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><th class="glossy"><a name="otherlayers"></a>其它圖層</th></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>B5000</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>1/5000基本地形圖</td></tr><tr><td>摘要</td><td>1/5000基本地形圖</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>CITY</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>縣市界</td></tr><tr><td>摘要</td><td>縣市界</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>EMAP16</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>臺灣通用電子地圖(不含等高線及門牌)</td></tr><tr><td>摘要</td><td>臺灣通用電子地圖(不含等高線及門牌)</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>EMAP2</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>臺灣通用電子地圖透明</td></tr><tr><td>摘要</td><td>臺灣通用電子地圖透明</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>EMAP5_OPENDATA</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>臺灣通用電子地圖(套疊等高線)opendata, 最大比例尺一萬八千分之一</td></tr><tr><td>摘要</td><td>臺灣通用電子地圖(套疊等高線)opendata, 最大比例尺一萬八千分之一</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>EMAP5</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>臺灣通用電子地圖(套疊等高線)</td></tr><tr><td>摘要</td><td>臺灣通用電子地圖(套疊等高線)</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>EMAP6_OPENDATA</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>臺灣通用電子地圖(不含等高線)opendata, 最大比例尺一萬八千分之一</td></tr><tr><td>摘要</td><td>臺灣通用電子地圖(不含等高線)opendata, 最大比例尺一萬八千分之一</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>EMAP6</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>臺灣通用電子地圖(不含等高線)</td></tr><tr><td>摘要</td><td>臺灣通用電子地圖(不含等高線)</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>EMAP7</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>taiwane-map(transparent)</td></tr><tr><td>摘要</td><td>taiwane-map(transparent)</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>EMAP8</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>taiwane-map(en)</td></tr><tr><td>摘要</td><td>taiwane-map(en)</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>EMAP</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>臺灣通用電子地圖</td></tr><tr><td>摘要</td><td>臺灣通用電子地圖</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>LANDSECT</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>段籍圖</td></tr><tr><td>摘要</td><td>段籍圖</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>LUIMAP</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>國土利用調查成果圖</td></tr><tr><td>摘要</td><td>國土利用調查成果圖</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>MB5000</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>1/5000圖幅框</td></tr><tr><td>摘要</td><td>1/5000圖幅框</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>SCHOOL</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>各級學校範圍圖</td></tr><tr><td>摘要</td><td>各級學校範圍圖</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>TOWN</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>鄉鎮區界</td></tr><tr><td>摘要</td><td>鄉鎮區界</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>Village</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>村里界</td></tr><tr><td>摘要</td><td>村里界</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr><tr><td><table width="100%"><tr><th class="glossy">屬性</th><th class="glossy">值</th></tr><tr><td>名稱</td><td>PHOTO2015</td></tr><tr><td>可見性</td><td>顯示</td></tr><tr><td>標題</td><td>正射影像圖104年</td></tr><tr><td>摘要</td><td>正射影像圖104年</td></tr><tr><td>可識別</td><td>否</td></tr><tr><td>可透明</td><td>是</td></tr><tr><td>可縮放</td><td>是</td></tr><tr><td>層疊數目</td><td>0</td></tr><tr><td>固定寬度</td><td>0</td></tr><tr><td>固定高度</td><td>0</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3857</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:4326</td></tr><tr><td>可用的坐標参考系統</td><td>EPSG:3826</td></tr><tr><td>樣式中可用</td><td><table width="100%"><tr><th class="glossy">名稱</th><td>default</td></tr><tr><th class="glossy">標題</th><td></td></tr><tr><th class="glossy">摘要</th><td></td></tr></table></td></tr></table></td></tr></table><p class="glossy">沒有資料值</p>
<p>*未設定無資料值*</p>
</p>
<p class="glossy">資料類型</p>
<p>無法確定影像資料的類型.</p>
<p class="glossy">金字塔概貌</p>
<p><p class="glossy">圖層的空間参考系統</p>
<p>+proj=tmerc +lat_0=0 +lon_0=121 +k=0.9999 +x_0=250000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs</p>
<p class="glossy">圖層範圍(圖層的原始源投影)</p>
<p>146336.7729999999864958,2370779.8739999998360872 : 370123.9660000000149012,2851009.9369999999180436</p>
<p class="glossy">
波段</p>
<p>波段 1</p>
<p>波段數</p>
<p>
1</p>
<p>沒有統計值</p>
<p>
尚未收集統計值</p>

**Comment by jie4922** [comment]
Don't know if paste above is okay for you to analysis?
Paste the origin output data into PDF file  : [outputdata.pdf](https://github.com/tomchadwin/qgis2web/files/743527/outputdata.pdf)

**Comment by jie4922** [comment]
By the way, I find that open layer search function will make OL3 map empty.
Even that layer name, field name, value and shp file name are all in English still make OL3 map empty.
![image](https://cloud.githubusercontent.com/assets/25398198/22492915/5c82cf28-e867-11e6-9bc3-a88fd2523fe3.png)
Once close the function the map work.
![image](https://cloud.githubusercontent.com/assets/25398198/22492944/86fc58b4-e867-11e6-860a-cef08af71848.png)

Test executed in English  environment.
Also maybe char problem?

**Comment by tomchadwin** [comment]
Yes, that's the problem. "版本" is "VERSION". I gave no solution for this yet, and have asked for help:

http://osgeo-org.1560.x6.nabble.com/WMS-metadata-in-non-English-locale-td5305601.html

**Comment by jie4922** [comment]
True, 「版本」means「version」in english. This problem should affect many non-English users acrossing world. Hope can be fixed. Thank you Tom, take this issue so seriously :)

**Comment by tomchadwin** [comment]
In the QGIS Python console again, can you type:

```
print QCoreApplication.translate("", "WMS Version")
```

What does it return?

**Comment by tomchadwin** [comment]
I've committed a fix which might get the Trad. Chinese environment working - not search yet, just displaying the layers. Can you let me know if the latest commit to master now allows a WMS to render with your local settings set to Trad. Chinese?

**Comment by jie4922** [comment]
1. I just download and try the latest master but still not work with Trad. Chinese setting.
![image](https://cloud.githubusercontent.com/assets/25398198/22524790/a09584ec-e8ff-11e6-8643-36f6bcf5af1f.png)

2. print QCoreApplication.translate("", "WMS Version") and return :
Python主控台
使用iface存取QGIS的API介面或鍵入help(iface) 獲取更多訊息
print QCoreApplication.translate("", "WMS Version")
WMS Version

![image](https://cloud.githubusercontent.com/assets/25398198/22524897/0bbaacca-e900-11e6-8ede-f375538926d4.png)

**Comment by tomchadwin** [comment]
Just to confirm, your client was set to Trad. Chinese for `print QCoreApplication.translate("", "WMS Version")`?

**Comment by jie4922** [comment]
Yes, confirmed. The menu bar, panel title, and partial console message were shown in Trad. Chinese so that's for sure.
Then I use another PC as client to test and get the same result as below:
![image](https://cloud.githubusercontent.com/assets/25398198/22531620/152e56f4-e91d-11e6-99af-4330e8b429d8.png)

print QCoreApplication.translate("", "WMS Version")
WMS Version

**Comment by tomchadwin** [comment]
That's disappointing. I don't have a solution for this problem yet. Obviously, I can tell you how to edit the exported code manually, but that's not a success for this plugin.

**Comment by jie4922** [comment]
Oh,that's really a bit pity. 
It's thankful if you can introduce me how to edit exported code manually.
Actually, I've modified some simple pieces (such as collapse, table decoration, legends an so on)to fit my need. :)

**Comment by tomchadwin** [comment]
OK, in your export, you need to open `/layers/layers.js` in a text editor. Then find the section which says eg:

```javascript
                          url: "http://wms.nlsc.gov.tw/wms",
                          params: {
                            "LAYERS": "PHOTO2",
                            "TILED": "true",
                            "VERSION": ""},
                        })),
```

Insert the `VERSION` value:

```javascript
                          url: "http://wms.nlsc.gov.tw/wms",
                          params: {
                            "LAYERS": "PHOTO2",
                            "TILED": "true",
                            "VERSION": "1.1.1"},
                        })),
```

**Comment by tomchadwin** [comment]
OK, I've committed a hack which might work. I've tested it with my own QGIS set to one of the bottom two pictogram-based languages - apologies that I don't know which is Trad. Chinese. Can you test it and let me know if that has fixed the problem for you?

**Comment by tomchadwin** [comment]
Actually, I might have solved it, but need you to test to confirm whether it works.

Can you set your QGIS locale to Trad. Chinese, open the QGIS Python console, and type the following:

```python
print QCoreApplication.translate("QgsWmsProvider", "WMS Version")
```

Let me know what is printed.

**Comment by jie4922** [comment]
Oh, seems work finally! Good job! 
![image](https://cloud.githubusercontent.com/assets/25398198/22553616/5f6ce688-e998-11e6-92d8-14f5804fe1d4.png)

Label and popup also seems work in Trad. Chinese with vector layer also the same language.
![image](https://cloud.githubusercontent.com/assets/25398198/22553737/c4008578-e998-11e6-8735-005755ea2c77.png)

print QCoreApplication.translate("QgsWmsProvider", "WMS Version")
WMS版本

**Comment by tomchadwin** [comment]
OK, great. Because you confirmed we got the localized text back, I've made another change and committed to master here, to get rid of the horrible hack. Can you copy down the latest version and test again?

Thanks for all the help in figuring this one out - I really appreciate how much time you've spent.

**Comment by tomchadwin** [comment]
Great. Can you test the layer search as well? I did some work yesterday to try to fix that. Is it working?

**Comment by jie4922** [comment]
Try and get console message :
-----------------------------------------------------------------------------------------------------------------
FAIL
Traceback (most recent call last):
  File "C:/Users/Jie/.qgis2/python/plugins\qgis2web\olwriter.py", line 95, in writeOL
    field=searchVals[1])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
------------------------------------------------------------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/25398198/22558394/756ca7e2-e9a8-11e6-8f36-bcd0b7ccf64e.png)

Is there any precondition such as each of the value should be unique?

**Comment by tomchadwin** [comment]
No, you can have duplicate conditions. This is just another ASCII-only bug. I've committed a change. Can you test now? If it still fails, can you upload a Trad. Chinese vector layer? I need something to test with.

**Comment by jie4922** [comment]
Empty map again. 
![image](https://cloud.githubusercontent.com/assets/25398198/22561099/dafd1282-e9b1-11e6-96a8-4bff2d90b1fe.png)

Trad. Chinese shp file：https://drive.google.com/file/d/0B01wuahjDBFGRnlqYzZvakQtSmM/view?usp=sharing
The third field "行政區" is the search target.

**Comment by tomchadwin** [comment]
Hmm. That's not working for me:

- layer only has two fields
- first field is `id`, second is `???`, whether I have QGIS set to English or to either of the bottom two locales in `Settings > Options > Locale`

Is this layer a shapefile when you use it, or have you exported it as a SHP for me and your copy is eg PostGIS, WFS, etc? I'm just wondering if SHP doesn't support non-ASCII.

And which language in the `Settings > Options > Locale` dropdown is Trad. Chinese? It would help my testing to be able to use the same settings as you.

**Comment by jie4922** [comment]
So weird~ There should be three fields and all carry Trad. Chinese field name.
![image](https://cloud.githubusercontent.com/assets/25398198/22596121/4809d848-ea65-11e6-8b6b-3ff5f440ac99.png)

That's the .shp what I use directly in my work. Just I cut a specific area's features for you to test because the original one's feature amount is bigger for more than 30 times. Otherwise, we are using the same shapefile.

The last language is Trad. Chinese.
![image](https://cloud.githubusercontent.com/assets/25398198/22596524/e0f416f8-ea66-11e6-848a-789eaa7ffd43.png)

And I can see all the three fields and their Trad. Chinese field name in English language setting as above.

**Comment by tomchadwin** [comment]
OK, I opened the SHP with QGIS locale already set to Trad. Chinese, and now it seems to have worked.

I've committed a change which perhaps makes things a little better. The map now displays when you select that field in `Layer search`. Can you confirm?

If you do have a map and a search icon, then next thing to check is whether the search actually works.

**Comment by jie4922** [comment]
Yes, the search icon appears now! But seems overlap the geolocate user icon.
![image](https://cloud.githubusercontent.com/assets/25398198/22613104/77d314e0-eab0-11e6-88f3-72750b99dfc6.png)

Maybe search not work yet. Try to enter something to search but seems always back to zoom level 1.

**Comment by tomchadwin** [comment]
Yes, the overlapping issue needs no be sorted (#391). Will have to investigate the other issue of the search not working.

**Comment by tomchadwin** [comment]
I'll close this issue, as I believe all things mentioned in it are either fixed, or now have their own tickets. Please reopen if required. To summarize:

- OpenLayers control no longer overlap
- WMTS now supported

Remaining issue:

- layer search fails with eg Trad. Chinese fields

**Comment by jie4922** [comment]
Understand. Thanks!
