### ISSUE TITLE
Leaflet scaleDependentLayerScript crashes QGIS

### ISSUE THREAD

**Issue by Sortronic** [tomchadwin/qgis2web#472]
OL3 doesn't have problem to render the map. If I switch to Leaflet I get this error and QGIS 2.18 crashes
![leafletcrash](https://cloud.githubusercontent.com/assets/25204391/24870183/7b4c17aa-1de3-11e7-88d0-4bfba9f9c663.png)

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by Sortronic** [comment]
Leaflet doesn't crash but it doesn't hide second layer.
The map has first layer with points set for visibility : 1:1,000,000,000 to 1:150,000.
Second layer lines set: 1:150,000 to 1:15.

The halo around the points are the visible lines that should be hidden.

![leaflet-sdv](https://cloud.githubusercontent.com/assets/25204391/24916144/4ee52dd6-1ea7-11e7-8c21-715ca21cd174.png)

**Comment by tomchadwin** [comment]
Confirmed. Investigating.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by Sortronic** [comment]
I have mixed results.
The first screen I get, still shows lines in the background.

![leaflet01](https://cloud.githubusercontent.com/assets/25204391/24965708/da3d941a-1f72-11e7-863c-0e4433a93c63.png)

If I zoom in one step they disappear.

![leaflet02](https://cloud.githubusercontent.com/assets/25204391/24965748/f72c80e0-1f72-11e7-968c-1dc1b772e08c.png)

At this level of zoom the point are supposed to be gone. And actually points not clustered are gone

![leaflet03](https://cloud.githubusercontent.com/assets/25204391/24966099/010458bc-1f74-11e7-9748-879b4117e67b.png)

Even when points are "declustered" they stay visible. In short once clustered, points don't take scale dependent visibility.

![leaflet04](https://cloud.githubusercontent.com/assets/25204391/24966492/132c250a-1f75-11e7-9d6d-de16f61b6b98.png)

**Comment by tomchadwin** [comment]
OK, so two issues:

1. Initial display of map ignores scale-dependency
2. Clusters ignore scale-dependency

Right?

**Comment by Sortronic** [comment]
yes

**Comment by tomchadwin** [comment]
Possibly related to #473

**Comment by tomchadwin** [comment]
Fix for 2 (clusters ignore scale-dependency) committed to master. Please test.

**Comment by tomchadwin** [comment]
Fix for 1 (initial display of map ignores scale-dependency) committed to master. Please test.

**Comment by dominijk** [comment]
Does the plugin support scale dependent visibility for SVG markers? It works for me in QGIS but not in preview or actual leaflet map through plugin
