### ISSUE TITLE
Leaflet multi-style layer highlight reset

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/qgis2web#510]
Doesn't work, and I don't know how to fix, as per #507.

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by joooeey** [comment]
This problem still occurs (on qgis2web 3.16.0) with the following layer:

![image](https://user-images.githubusercontent.com/28426758/161053494-902c70d7-5e40-42e9-8766-12199c7c3d7c.png)

Every point that I hover over stays blue forever.

**Comment by andreaordonselli** [comment]
I have just released version [3.19.0](https://github.com/qgis2web/qgis2web/releases/tag/v3.19.0), which fixes the issues discussed in this thread. Shortly, the update will be available within the QGIS plugin repository.

Thank you for using the plugin.

I would greatly appreciate it if you would consider donating a virtual coffee through the button on the homepage to support the development of qgis2web.

Best regards.
