### ISSUE TITLE
Please help!!!! UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 361: character maps to 

### ISSUE THREAD

**Issue by diwaspant** [tomchadwin/qgis2web#624]
While exporting the shapefile to web the following error occurred: 

An error has occurred while executing Python code: 

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 361: character maps to 
Traceback (most recent call last):
  File "C:/Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 326, in saveMap
    feedback=self.feedback)
  File "C:/Users/...../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 90, in write
    folder=dest_folder)
  File "C:/Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olwriter.py", line 129, in writeOL
    popup, json, restrictToExtent, extent, feedback, matchCRS)
  File "C:/Users/...../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 182, in exportLayers
    iface, extent, precision, crs, optimize)
  File "C:/Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 209, in exportVector
    for line in tmpFile:
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 361: character maps to 

Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.0.0-Girona Girona, 001c80b0c3 

Python Path:
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python
C:/Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/....../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.0\bin\python36.zip
C:\PROGRA~1\QGIS3~1.0\apps\Python36\DLLs
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib
C:\Program Files\QGIS 3.0\bin
C:\PROGRA~1\QGIS3~1.0\apps\Python36
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages
C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\....\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\.....\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

**Comment by tomchadwin** [comment]
Do any of your field names contain special characters? If so, can you try changing them to plain a-zA-Z0-9?

**Comment by diwaspant** [comment]
Yes, it contains Unicode values in various field (Nepali Script). I want the plugin to support unicode as well. Is there any way ? And I am very new to QGIS and python.

**Comment by tomchadwin** [comment]
Try changing the field names to ASCII. You can then try adding aliases to the fields in NepalI Script.

**Comment by diwaspant** [comment]
I have the field names in ASCII but the field values in Nepali Script. 
Hope this can be solved.
![image](https://user-images.githubusercontent.com/37430699/37591369-6b3e7fba-2b93-11e8-8cd5-ca45d97b0f7c.png)

**Comment by tomchadwin** [comment]
I've just changed a value in a field to a non-ASCII character, and the export worked fine, so the problem must lie elsewhere. Are you able to upload your layer file for me to test?

**Comment by tomchadwin** [comment]
Closed without further feedback. Do comment here and I can reopen.

**Comment by tomchadwin** [comment]
Reopening to catch duplicate issues #632 and #640

**Comment by tomchadwin** [comment]
I've committed a possible fix to master, but since I've been unable to recreate the problem myself, I do need someone else to test it. @diwaspant, @1900g, @JesusLopTem, @4nnabe can you install current master and test? Alternatively, just make the change I made in this commit in your local copy:

https://github.com/tomchadwin/qgis2web/commit/463881e9ba6bd8d16caf595f53659ff42db36430

Remember you need to restart QGIS or use Plugin Reloader once you've made the change.

**Comment by tomchadwin** [comment]
Ah, that's a different error. Let me investigate. Thanks for testing.

**Comment by diwaspant** [comment]
**Still the same error:

An error has occurred while executing Python code: 

UnicodeEncodeError: 'charmap' codec can't encode characters in position 133-139: character maps to 
Traceback (most recent call last):
  File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 314, in previewMap
    preview_file = self.createPreview()
  File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 277, in createPreview
    dest_folder=utils.tempFolder()).index_file
  File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 101, in write
    folder=dest_folder)
  File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 188, in writeLeaflet
    exp_crs, minify)
  File "C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\utils.py", line 213, in exportVector
    f.write(line)
  File "C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 133-139: character maps to 


Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.0.2-Girona Girona, 307d082e3d 

Python Path:
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.0\bin\python36.zip
C:\PROGRA~1\QGIS3~1.0\apps\Python36\DLLs
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib
C:\Program Files\QGIS 3.0\bin
C:\PROGRA~1\QGIS3~1.0\apps\Python36
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\Pythonwin
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview
C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res
C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\user\AppData\aRoaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\shapetools\ext-libs*

**Comment by tomchadwin** [comment]
No, it is a different error. I should have something for you to test in a few minutes.

**Comment by tomchadwin** [comment]
OK, I've added another fix (https://github.com/tomchadwin/qgis2web/commit/9d6c769f595d4150409e471bfd2ae7b9033083ed). Can you test again? Thanks.

**Comment by diwaspant** [comment]
Thanks, works perfectly 👍 👍 👍 👍 👍 
@tomchadwin

**Comment by tomchadwin** [comment]
Ah, brilliant! Thanks again for testing. It would be good to hear from someone else, too, just to be sure it is fixed (I don't like debugging blind...)

**Comment by JesusLopTem** [comment]
Works fine here too. Thanks @tomchadwin !

**Comment by tomchadwin** [comment]
Fantastic. Thanks, very much, both!

**Comment by PatrickStotz** [comment]
I had the same error and can confirm that both fixes together do the trick. 👍

**Comment by tomchadwin** [comment]
Released as 3.1.0 and pushed to QGIS plugins repo.

**Comment by 4nnabe** [comment]
I updated the plugin and now it works fine for me as well - as long as I don't use ä,ü,ö in the path of the export folder. Thanks a lot!

**Comment by tomchadwin** [comment]
@4nnabe OK, I'll try to look into the path issue when I can. Thanks for testing, and also to @PatrickStotz!

**Comment by tomchadwin** [comment]
@4nnabe Can you post the error you get when you have special characters in your path? Thanks.

**Comment by 4nnabe** [comment]
Sure, this is the error I get:

```Ein Fehler trat bei der Ausführung von Python-Code auf: 

UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 38: ordinal not in range(128) 
Traceback (most recent call last):
  File "/Users/anna/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 334, in saveMap
    webbrowser.open_new_tab(self.exporter.destinationUrl())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/webbrowser.py", line 68, in open_new_tab
    return open(url, 2)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/webbrowser.py", line 60, in open
    if browser.open(url, new, autoraise):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/webbrowser.py", line 606, in open
    osapipe.write(script)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 38: ordinal not in range(128)


Python-Version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] 
QGIS-Version: 3.0.2-Girona Girona, exported```

**Comment by celestialbunny** [comment]
`from countryinfo import CountryInfo

country = CountryInfo('Singapore')
country.currencies()`

will produce such an error:
`Traceback (most recent call last):
  File "country.py", line 4, in <module>
    country = CountryInfo('Singapore')
  File "C:\Users\coron\AppData\Local\Programs\Python\Python37-32\lib\site-packages\countryinfo\countryinfo.py", line 30, in __init__
    country_info = json.load(open(file_path))
  File "C:\Users\coron\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\coron\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line
23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 49: character maps to <undefined>`

I am using Windows 10, 64-bit running Python 3.7.2 32-bit
This is my first week into python so any form of explanation/help is very appreciated.

**Comment by tomchadwin** [comment]
@celestialbunny That error doesn't seem to come from qgis2web, whereas the previous people in this thread were using it.

**Comment by celestialbunny** [comment]
Well ah, adding in the format type does seem to help solve my problem `json.load(open(file_path, format="utf-8")`. Just letting you know, in case it comes in handy in future~ Thanks for responding.

**Comment by pulsebeat14** [comment]
You can use Pillow 
install module - 
pip install Pillow==2.2.1

**Comment by SandipSPatil** [comment]
I am new in Python, I have installed pyiwn and executed following command, but showing error, anybody please help me to out from this error....
>>iwn = pyiwn.IndoWordNet()
2020-08-27:16:35:07,116 INFO     [iwn.py:43] Loading hindi language synsets...
Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    iwn = pyiwn.IndoWordNet()
  File "C:\Python\lib\site-packages\pyiwn\iwn.py", line 45, in __init__
    self._synset_df = self._load_synset_file(lang.value)
  File "C:\Python\lib\site-packages\pyiwn\iwn.py", line 51, in _load_synset_file
    synsets = list(map(lambda line: self._load_synset(line), f.readlines()))
  File "C:\Python\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 13: character maps to <undefined>

**Comment by shivani1308** [comment]
line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5859: character maps to <undefined>
