### ISSUE TITLE
Error when exporting to OpenLayers with grid enabled

### ISSUE THREAD

**Issue by glompos21** [tomchadwin/qgis2web#636]
An error has occurred while executing Python code: 

TypeError: getStrokeStyle() missing 1 required positional argument: 'linejoin' 
Traceback (most recent call last):
  File "/home/glompos21/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 326, in saveMap
    feedback=self.feedback)
  File "/home/glompos21/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 90, in write
    folder=dest_folder)
  File "/home/glompos21/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 174, in writeOL
    grid = getGrid(project)
  File "/home/glompos21/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olScriptStrings.py", line 515, in getGrid
    strokeStyle = getStrokeStyle(color, dashed, width, linecap, linejoin)
TypeError: getStrokeStyle() missing 1 required positional argument: 'linejoin'

Python version: 3.6.5rc1 (default, Mar 14 2018, 06:54:23) [GCC 7.3.0] 
QGIS version: 3.0.1-Girona Girona, a86bec2 
qgis2web version	3.0.0

The error occures when the Grid is enebled (View -> Decoration-> Grid)

**Comment by tomchadwin** [comment]
Fix committed to master. Please test.

**Comment by glompos21** [comment]
Problem still here:
An error has occurred while executing Python code: 

TypeError: getStrokeStyle() missing 1 required positional argument: 'linejoin' 
Traceback (most recent call last):
  File "/home/glompos21/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/maindialog.py", line 326, in saveMap
    feedback=self.feedback)
  File "/home/glompos21/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 90, in write
    folder=dest_folder)
  File "/home/glompos21/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olwriter.py", line 174, in writeOL
    grid = getGrid(project)
  File "/home/glompos21/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/olScriptStrings.py", line 520, in getGrid
    strokeStyle = getStrokeStyle(color, dashed, width, linecap, linejoin)
TypeError: getStrokeStyle() missing 1 required positional argument: 'linejoin'

**Comment by tomchadwin** [comment]
My apologies. I've committed another fix to master. Can you try it now?

**Comment by tomchadwin** [comment]
I think this is now fixed, and released as 3.0.1 - please update qgis2web and let us know.
