### ISSUE TITLE
Tables in Layermanager cause plugin to crash

### ISSUE THREAD

**Issue by frankbroniewski** [tomchadwin/qgis2web#637]
This is on the latest OSGeo4W64 QGIS3 build with the most recent version of the plugin.
Having a table in the layer manager causes the plugin to crash on start. I had a virtual layer with some generated statistics with no geometry. Calling the plugin causes the following error:

`WARNING	Traceback (most recent call last):
			  File "C:/Users/Frank/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\qgis2web.py", line 60, in run
			    self.dlg = MainDialog(self.iface)
			  File "C:/Users/Frank/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 132, in __init__
			    self.populate_layers_and_groups(self)
			  File "C:/Users/Frank/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 349, in populate_layers_and_groups
			    testDump = layer.renderer().dump()
			AttributeError: 'NoneType' object has no attribute 'dump'`

**Comment by tomchadwin** [comment]
Can you try current master? I think that issue is fixed already.

**Comment by frankbroniewski** [comment]
Hi Tom,
I cloned the GIT today and copied the plugin to my QGIS 3 plugin directory. Unfortunately, the error still occurs, and there's more now

```Traceback (most recent call last):
			  File "C:/Users/Frank/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 350, in populate_layers_and_groups
			    testDump = layer.renderer().dump()
			AttributeError: 'NoneType' object has no attribute 'dump'
			
			During handling of the above exception, another exception occurred:
			
			Traceback (most recent call last):
			  File "C:/Users/Frank/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\qgis2web.py", line 60, in run
			    self.dlg = MainDialog(self.iface)
			  File "C:/Users/Frank/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 132, in __init__
			    self.populate_layers_and_groups(self)
			  File "C:/Users/Frank/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 362, in populate_layers_and_groups
			    level=QgsMessageLog.CRITICAL)
			AttributeError: type object 'QgsMessageLog' has no attribute 'CRITICAL'```

I've created a small test case - just a few kb - wich you can download here: http://www.frankbroniewski.com/files/qgis2web_error.zip

**Comment by tomchadwin** [comment]
Ah, apologies. There was a remaining bit of incompatible QGIS2 code in the error handler. Can you try master now?

**Comment by frankbroniewski** [comment]
Hi Tom,

I tried it just now and I am still seeing the error

```
2018-04-17T20:50:45	CRITICAL	Traceback (most recent call last):
			  File "C:/Users/Frank/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 351, in populate_layers_and_groups
			    testDump = layer.renderer().dump()
			AttributeError: 'NoneType' object has no attribute 'dump'
```

but! the plugin continues to work. I tried with my above mentioned test case. I noticed that OpenLayers fails to render the three points, but I guess this is another issue. If you need me to try another time just give me a short notice.

**Comment by tomchadwin** [comment]
Yeah, it's trapping the error which is expected, so don't worry. OL not outputing the points is temporarily solved by deleting the `declutter` line in the exported code - search the issues here for declutter (or it might be on Stack Exchange), and you should find out which exported file that is in.

**Comment by tomchadwin** [comment]
https://github.com/tomchadwin/qgis2web/issues/632
