### ISSUE TITLE
replace ?request=getcapabilities by request=gettile on wmts url

### ISSUE THREAD

**Issue by pvgenuchten** [tomchadwin/qgis2web#722]
It was reported [here](https://geoforum.nl/t/qgis2web-toont-geen-ondergrond/2528), small analysis made me conclude, if wmts url is added to qgis as ..../wmts?request=getcapabilities, qgis2web-leaflet-implementation does add &request=gettile (in stead of replace) to this endpoint causing all tilerequest to be getcapabilities requests.

**Comment by tomchadwin** [comment]
Do you have such an endpoint which I could use to test?

**Comment by tomchadwin** [comment]
Possible fix committed to master. Please test and report back.

**Comment by pvgenuchten** [comment]
> Do you have such an endpoint which I could use to test?

The problem is not that much in the endpoint, but more how the endpoint is loaded into qgis. The original issue talks about a layer 'luchtfoto' loaded from a qgis plugin called 'pdok'.
 
the wms url is added to qgis by the plugin as:

![image](https://user-images.githubusercontent.com/299829/66606938-6ce2ff80-ebb3-11e9-8fcd-b88daa70aece.png)

**Comment by pvgenuchten** [comment]
I tried with latest master, but i still see this output in html:

```
var layer_Luchtfoto2016Ortho25cmRGB_0 = L.tileLayer.wmts('https://geodata.nationaalgeoregister.nl/luchtfoto/rgb/wmts?request=GetCapabilities&service=WMTS', {
```

probably because the replace is case sensitive

**Comment by Jeroen-GroeneBij** [comment]
Hi,

Could this issue be re-opened please?
I have the same or similar issues using the WM(T)S maps from the PDOK services plugin (PDOK is the Dutch public data service).

Opening WM(T)S layers using the plugin in QGIS 3.10.4 work fine. Exporting them with Q2W doesn't.
The difficulty being it does work with some layers and doesn't with others.

It is easy to try, install the PDOK services plugin and from the plugin:

Select (or search) Luchtfoto Actueel Ortho 25cm RGB which is a WMTS.
Export with Q2W (Leaflet) gives an empty map.

Select (or search) gebouw_vlak [top10nlv2:Gebouw_vlak_style] and zoom in. This is a WMS.
Export to Q2W (Leaflet) and the map will be fine.

Select (or search) waterschapsgrens [wsaeenhedeninspire:waterschappen_pastel] which is a WMS.
Export with Q2W (Leaflet) and the map will only show the borders and not the symbology.

I have no idea what is going wrong.

**Comment by tomchadwin** [comment]
I can't get this to work, and am hampered by not speaking Dutch. Can anyone point me towards a live Leaflet map using a PDOK WMTS?

**Comment by Jeroen-GroeneBij** [comment]
I'll build all three for you, using the three examples. Give me a few minutes :)

**Comment by pvgenuchten** [comment]
the problem is that the service url is registered as wmts?request=GetCapabilities&service=WMTS, qgis/leaflet just concatenates &request=gettile, which results in:
wmts?request=GetCapabilities&service=WMTS&request=gettile, this is not a valid wmts request

i think qgis should remove ?request=getcapabilities before delegating it to leaflet

**Comment by tomchadwin** [comment]
> i think qgis should remove ?request=getcapabilities before delegating it to leaflet

But in this case, if I edit the output to make that change, it still doesn't work - that's what I'm stuck on.

**Comment by Jeroen-GroeneBij** [comment]
you can find the maps here: 
[www.groenebij.nl/Demo/luchtfoto_WMTS](url)
[www.groenebij.nl/Demo/gebouwvlak_WMS](url)
[www.groenebij.nl/Demo?waterschap_WMS](url)

interestingly, gebouwvlak_WMS only works when adding a second layer, in this case Dutch municipalities. But then the second layer overlays the first one...??

**Comment by tomchadwin** [comment]
@Jeroen-GroeneBij My apologies - I meant a *working* example of a PDOK WMTS Leaflet map, not necessarily a qgis2web one.

**Comment by Jeroen-GroeneBij** [comment]
hahaha, no problem.

Good question. I have found this [https://github.com/NieneB/webmapping_for_beginners_v2](url)
which uses TMS in stead of WMTS.
In a post somewhere else she mentions difficulties with WMTS in Leaflet and also refers to [https://github.com/mylen/leaflet.TileLayer.WMTS](url)

Does this help in anyway?

**Comment by tomchadwin** [comment]
*waves @NieneB*

**Comment by Jeroen-GroeneBij** [comment]
I also see comments about PDOK offering their services mostly in CRS EPSG:28992 whereas Leaflet is tuned to WGS 84.  Those comments often refer to using Proj4 setings, which is beyond my comfort zone :)

**Comment by tomchadwin** [comment]
That should work - set your project to that CRS, and check "Match project CRS" in the qgis2web dialog.

**Comment by Jeroen-GroeneBij** [comment]
That doesn't seem to work. I use EPSG:28992 as my default CRS in qgis. So the project CRS is set to EPSG:28992.
check or uncheck Match project CRS makes no difference.

**Comment by tomchadwin** [comment]
I don't think the CRS is the problem here. The problem is this WMTS.

**Comment by Jeroen-GroeneBij** [comment]
Okay, I'll keep searching for information. Hopefully NieneB has some good advice.

**Comment by Jeroen-GroeneBij** [comment]
Do you have an example of a working WMTS Leaflet map not from PDOK? So I can compare the requests and parameters used in the html code.

**Comment by tomchadwin** [comment]
The provider I have always used for testing is https://wmts.nlsc.gov.tw/wmts.

**Comment by Jeroen-GroeneBij** [comment]
Hmm,
can you reproduce the following error?
QGIS 3.10.4 and q2w 3.12.1
add WMTS layer:
https://geodata.nationaalgeoregister.nl/tiles/service/wmts?&request=GetCapabilities&service=WMTS
no login required
choose layer brtachtergrondpastel with tileset EPSG:28992 and CRS EPSG:28992
In my case this opens a zoomed out map of The Netherlands.
Then run q2w:
I am getting the following Python error:

2020-04-03T12:17:48     WARNING    Traceback (most recent call last):
              File "C:/Users/Jeroen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 190, in changeFormat
              self.autoUpdatePreview()
              File "C:/Users/Jeroen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 334, in autoUpdatePreview
              self.previewMap()
              File "C:/Users/Jeroen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 337, in previewMap
              preview_file = self.createPreview()
              File "C:/Users/Jeroen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\maindialog.py", line 300, in createPreview
              dest_folder=utils.tempFolder()).index_file
              File "C:/Users/Jeroen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 101, in write
              folder=dest_folder)
              File "C:/Users/Jeroen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletWriter.py", line 282, in writeLeaflet
              minZoom, maxZoom)
              File "C:/Users/Jeroen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\leafletScriptStrings.py", line 319, in wmsScript
              wmts_style = d['styles'][0]
             KeyError: 'styles'

**Comment by tomchadwin** [comment]
OK, both the Python error WMTS and the PDOK plugin WMTS now work with current master. I've stripped off the whole WMTS URL querystring. Please can yo utest and let me know if this has improved things, @Jeroen-GroeneBij @pvgenuchten? Thanks!

**Comment by Jeroen-GroeneBij** [comment]
Could you please remind how to get the updated file? When I manually apply the changes Qgis gives another python erorr on startup.

**Comment by Jeroen-GroeneBij** [comment]
Did a new manual change: simply replaced the old line 315 with the new line 315. No error on startup, however, no solution for me. q2w is giving the exact same python error as above.

**Comment by tomchadwin** [comment]
Go to the front page of this repo, download the zip via the green button, find `leafletScriptStrings.py` in there (`/qgis2web/qgis2web/leafletScriptStrings.py`), copy it, and paste it into your qgis2web plugin directory. Then restart QGIS.

**Comment by Jeroen-GroeneBij** [comment]
Thank you

No more errors with the PDOK example, and, as long as don't check Match CRS, the WMTS map is visible. 
However I still notice two issues:
First, the WMTS layer should be the topmost layer. It is in the QGIS project and it is according to the layers list, but the second layer is the only one visble. If I turn that layer off in the webmap, the WMTS becomes visible. In the index.html the WMTS layer is also created at the end of the file, not as the first var layer.

Secondly, the WMTS layer is placed differently (off set?) and scaled differently from the second layer. The second and thus visible layer is centered and zoomed in to the center of The Netherlands. The WMTS is centered somewhere at the northenmost tip of The Netherlands.
When trying to zoom or pan the webpage gets messed up.
See the atached export.
[TEST_WMTS_PDOK.zip](https://github.com/tomchadwin/qgis2web/files/4427368/TEST_WMTS_PDOK.zip)

**Comment by tomchadwin** [comment]
Not sure about the layer order - I'll investigate. The other issue is the projection. Can you check that:

- your project and layer projections match
- you have checked "Match project CRS" in qgis2web

**Comment by Jeroen-GroeneBij** [comment]
Project CRS and layer CRS are the same (RD Amersfoort New, EPSG:28992).
See in the map attached what happens when I check the Match Project CRS in q2w.
When I open the map in Firefox I get a warning the page is slowing down the browser. It shows me it is trying to connect or is connected to 'https://geodata.nationaalgeoregister.nl and a few seconds later the map is visible, but the wmts is not visible. The layer as such is visible: when you add something to the attribution of the layer, the added attribution ill show.

[test_wmts_pdok_macthCRS.zip](https://github.com/tomchadwin/qgis2web/files/4428249/test_wmts_pdok_macthCRS.zip)

**Comment by tomchadwin** [comment]
I think I've fixed the layer order issue - as before, get the latest from master branch here, and this time overwrite `leafletWriter.py` and `leafletScriptString.py`. Let me know if that fixes it.

I don't yet understand the projection issue.

**Comment by tomchadwin** [comment]
OK, when you add the WMTS to QGIS via the PDOK plugin, make sure you drop down the menu to select EPSG:3857. Then make sure you *don't* check "Match project CRS" in qgis2web. That fixes it for me. Let me know.

**Comment by Jeroen-GroeneBij** [comment]
Well, at least now the WMTS is visible and correctly positioned and scaled. I do notice serious rendering issues when zooming and panning. I have to switch the layer on and off regularly to restore the image.
I do not know if this a server issue, or browser issue, internet connection issue or code.

Also this solution is using a different projection, which, to be honest is not a big deal in most of my projects.
I also tested it quickly with another PDOK wmts using EPSG:28992 
This map now also is visible, but position and scaling are wrong.
Using EPSG:3857 the position and scaling is correct.

Is it fair to say there seems to be an issue with the combination EPSG:28992 and WMTS and Leaflet?

**Comment by tomchadwin** [comment]
I think there is an issue with rasters in non-3857 in Leaflet, but we're reaching the limit of my knowledge, I'm afraid. Can we perhaps call this one fixed, and close it down for now? We've solved a few issues, and I'm not sure what else we can achieve. For what it's worth, OpenLayers handles raster reprojection client-side (as I recall), so you might have better results.

**Comment by Jeroen-GroeneBij** [comment]
Thanks Tom, indeed some issues are solved.
I will ask around in other fora (such as the one for PDOK) and point them to this issue and see if some one can help.

**Comment by tomchadwin** [comment]
OK, closing for now - will reopen if required.

**Comment by tomchadwin** [comment]
Released as 3.13.0 and pushed to QGIS plugins repo.

**Comment by emacgillavry** [comment]
For the Dutch RD projection (EPSG:28992) used in the Netherlands, there is a custom tilegrid to be used. Not only the projection differs from EPSG:3857 (Spherical Mercator), but also the zoom levels don't align. While zoom level 0 in EPSG:3857 covers most of the world, zoom level 0 for he Dutch tile grid only covers the Dutch continental shelf.

So, this is genuinely a different issue and I'd suggest to track this outside of the scope of this replace issue should you wish to accommodate multiple tilegrids in this plugin.

**Comment by pvgenuchten** [comment]
But those scale levels are advertised in wmts capabilities, openlayers doesn't pick that up automatically? oh wait, this is leaflet, so you may have to code that explictly
