### ISSUE TITLE
Raster Layers don´t work 

### ISSUE THREAD

**Issue by CopterC** [tomchadwin/qgis2web#897]
Hi,
unfortunately all raster layers don´t work with QGIS2web since the latest update. The raster layers are only displayed in the preview, when the OpenStreetMap is deactivated. But when I try to export it, there is no raster image displayed. The folder also contains no raster image.
It worked well before I updated QGIS2web. Have you a solution for me? I use QGIS 3.10.6.

Best regards
Leon

**Comment by tomchadwin** [comment]
Please upload your project and layers files here. Without them, it's impossible to know what the specific problem is. Simplify down to a single layer if you can.

**Comment by tomchadwin** [comment]
I've just tested raster export in all three formats, and it is working. It must be something more specific. Please upload your files.

**Comment by CopterC** [comment]
This is very simplified, but it also doesn´t work. 
https://we.tl/t-pkrap4ZEAD

Thanks for your help!

**Comment by tomchadwin** [comment]
Hrm. Leaflet is putting the raster under the tiles. I'll have to investigate. Can you export in OpenLayers format instead? That works.

By the way, you can drag and drop a zip onto a reply here, and it will attach directly.

**Comment by CopterC** [comment]
No, it only displays a white space when I open it in Google Chrome or Firefox. 

Ah okay, I will do it when I have to upload something next time.

**Comment by tomchadwin** [comment]
Possible fix committed to master. Please test and report back.

**Comment by CopterC** [comment]
Hey Tom,
I tried to export my web map after I have seen that there is a new update. Unfortunately it is still not working, there is no raster layer displayed. I also can´t find an .png image of it in the export folders.

Thanks for your help!
Leon

**Comment by tomchadwin** [comment]
I don't have your project and layers files any more, and the link has expired. Can you upload the currently failing ones?

**Comment by CopterC** [comment]
Yes, here are the files:
[QGIS2WEB_Fehler.zip](https://github.com/tomchadwin/qgis2web/files/4830520/QGIS2WEB_Fehler.zip)

**Comment by tomchadwin** [comment]
Point pattern fills are unsupported. If you change that to a simple fill, it should work.

**Comment by CopterC** [comment]
I deleted the layer, but it also doesn´t work...
Even when I delete all except the raster layer, nothing is displayed or even exported. Not in other projects either.

**Comment by tomchadwin** [comment]
Very odd. It works for me. Let me do one and upload it.

**Comment by CopterC** [comment]
[qgis2web_2020_06_26-14_06_15_277749.zip](https://github.com/tomchadwin/qgis2web/files/4836817/qgis2web_2020_06_26-14_06_15_277749.zip)

Here is an example of an export.

**Comment by tomchadwin** [comment]
I'll take a look when I can. In the meantime, here are my exports of your project:

https://tom.chadw.in/maps/raster_issue/openlayers/
https://tom.chadw.in/maps/raster_issue/leaflet/

MBGLJS doesn't work - will have to investigate later.

**Comment by CopterC** [comment]
Weird... The measure icon is also not displayed in my export, in your version it works..

**Comment by tomchadwin** [comment]
You are using http: instead of https: for your OSM tiles. That causes security issues, so if you can correct that, that might bring everything back to life for you. Let me know.
